- include: dotfile_file.yml
  with_items:
    - .gitconfig-aliases

- name: Ensure Zsh reads /etc/profile
  blockinfile:
    dest: /home/{{ millennium_falcon.pilot }}/.gitconfig
    block: |
      [include]
          path = .gitconfig-aliases
    owner: "{{ millennium_falcon.pilot }}"
    group: "{{ millennium_falcon.crew }}"
    mode: 0644
