- name: Ensure Zsh reads /etc/profile
  blockinfile:
    dest: /home/{{ millennium_falcon.pilot }}/.gitconfig
    block: |
      [include]
          path = /home/{{ millennium_falcon.pilot }}/Projects/cfg/git/.gitconfig-aliases
    owner: "{{ millennium_falcon.pilot }}"
    group: "{{ millennium_falcon.crew }}"
    mode: 0644
