- include_tasks: dotfile_file.yml
  with_items:
    - .gitconfig-aliases

- name: 'Settings : Git : Ensure aliases are included in .gitconfig'
  blockinfile:
    dest: /home/{{ millennium_falcon.pilot }}/.gitconfig
    block: |
      [include]
          path = .gitconfig-aliases
    owner: '{{ millennium_falcon.pilot }}'
    group: '{{ millennium_falcon.crew }}'
    mode: 0644
