- import_tasks: system.yml
  tags:
    - system-settings

- import_tasks: atom.yml
  tags:
    - atom-settings

- import_tasks: zsh.yml
  tags:
    - zsh-settings

- import_tasks: git.yml
  tags:
    - git-settings

- import_tasks: konsole.yml
  tags:
    - konsole-settings

- import_tasks: krusader.yml
  tags:
    - krusader-settings
