- name: 'Settings : System : Set time and date automatically'
  command: timedatectl set-ntp true

- include_tasks: dotfile_file.yml
  with_items:
    - .config/kdeglobals
    - .config/plasmarc
    - .config/kxkbrc
    - .config/kcminputrc
    - .config/ksplashrc
    - .config/kwinrc
    - .config/kscreenlockerrc
    - .config/kaccessrc
    - .config/kactivitymanagerd-pluginsrc
    - .config/kactivitymanagerdrc
    - .config/breezerc
    - .config/oxygenrc
    - .config/kglobalshortcutsrc
    - .config/khotkeysrc
    - .config/kuriikwsfilterrc
    - .config/baloofilerc
    - .config/krunnerrc
    - .config/powermanagementprofilesrc
    - .config/plasma-org.kde.plasma.desktop-appletsrc
    - .config/bluedevil.notifyrc
    - .config/digikam.notifyrc
    - .config/freespacenotifier.notifyrc
    - .config/k3b.notifyrc
    - .config/kaccess.notifyrc
    - .config/kcm_touchpad.notifyrc
    - .config/kdeconnect.notifyrc
    - .config/kdenlive.notifyrc
    - .config/konsole.notifyrc
    - .config/konversation.notifyrc
    - .config/ksmserver.notifyrc
    - .config/kstars.notifyrc
    - .config/ksysguard.notifyrc
    - .config/ktorrent.notifyrc
    - .config/kwalletd.notifyrc
    - .config/kwin.notifyrc
    - .config/kwrited.notifyrc
    - .config/networkmanagement.notifyrc
    - .config/phonon.notifyrc
    - .config/plasma_workspace.notifyrc
    - .config/policykit1-kde.notifyrc
    - .config/powerdevil.notifyrc
    - .config/printmanager.notifyrc
    - .config/proxyscout.notifyrc
    - .config/spectacle.notifyrc
    - .gtkrc-2.0
    - .gtkrc-2.0-kde4
    - .config/gtk-3.0/settings.ini
    - .kde4/share/apps/color-schemes/Breath.colors
    - .kde4/share/apps/color-schemes/Maia Dark.colors
    - .kde4/share/apps/color-schemes/Maia.colors
    - .kde4/share/config/kdeglobals
    - .kde4/share/config/kdiff3rc
