- name: 'Settings : System : Set time and date automatically'
  command: timedatectl set-ntp true

- include_tasks: dotfile_file.yml
  with_items:
    - .config/kdeglobals
    - .config/kxkbrc
    - .config/kcminputrc
    - .config/ksplashrc
    - .config/kwinrc
    - .config/kscreenlockerrc
    - .config/kaccessrc
    - .config/kglobalshortcutsrc
    - .config/khotkeysrc
    - .config/baloofilerc
    - .config/touchpadrc
