- name: 'Settings : zsh : Set zsh as a shell for root and {{ millennium_falcon.pilot }}'
  user:
    name: '{{ item }}'
    shell: /bin/zsh
  with_items:
    - root
    - '{{ millennium_falcon.pilot }}'
- name: 'Settings : zsh : Ensure zsh reads /etc/profile'
  template:
    src: zprofile.j2
    dest: /etc/zsh/zprofile
    owner: root
    group: root
    mode: 0644
    backup: yes
- name: 'Settings : zsh : Link .zshrc for root and {{ millennium_falcon.pilot }}'
  file:
    src: /home/{{ millennium_falcon.pilot }}/Projects/cfg/home/.zshrc
    dest: '{{ item.home }}/.zshrc'
    state: link
    force: true
    owner: '{{ item.user }}'
    group: '{{ item.user }}'
  with_items:
    - user: '{{ millennium_falcon.pilot }}'
      home: /home/{{ millennium_falcon.pilot }}
    - user: root
      home: /root
- name: 'Settings : zsh : Set up .zshenv for root and {{ millennium_falcon.pilot }}'
  lineinfile:
    dest: '{{ item.home }}/.zshenv'
    line: ZSH=/home/{{ millennium_falcon.pilot }}/Projects/oh-my-zsh
    create: true
    owner: '{{ item.user }}'
    group: '{{ item.user }}'
  with_items:
    - user: '{{ millennium_falcon.pilot }}'
      home: /home/{{ millennium_falcon.pilot }}
    - user: root
      home: /root
