- name: Set Zsh as a shell for root and pilot
  user:
    name: "{{ item }}"
    shell: /bin/zsh
  with_items:
    - root
    - '{{ millennium_falcon.pilot }}'
- name: Ensure Zsh reads /etc/profile
  template:
    src: zprofile.j2
    dest: /etc/zsh/zprofile
    owner: root
    group: root
    mode: 0644
    backup: yes
- name: Link .zshrc for root and pilot
  file:
    src: /home/{{ millennium_falcon.pilot }}/Projects/cfg/home/.zshrc
    dest: "{{ item.home }}/.zshrc"
    state: link
    force: true
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
  with_items:
    - user: '{{ millennium_falcon.pilot }}'
      home: /home/{{ millennium_falcon.pilot }}
    - user: root
      home: /root
- name: Set up .zshenv for root and pilot
  lineinfile:
    dest: "{{ item.home }}/.zshenv"
    line: "ZSH=/home/{{ millennium_falcon.pilot }}/Projects/oh-my-zsh"
    create: true
    owner: "{{ item.user }}"
    group: "{{ item.user }}"
  with_items:
    - user: '{{ millennium_falcon.pilot }}'
      home: /home/{{ millennium_falcon.pilot }}
    - user: root
      home: /root
