language: generic

sudo: required

env:
  - distribution: ubuntu
    version: 14.04
  - distribution: ubuntu
    version: 16.04

services:
  - docker

before_install:
  - ./tests/travis_scripts/before_install.sh

install:
  - ./tests/travis_scripts/install.sh

script:
  - ./tests/travis_scripts/script.sh
