#!/usr/bin/env ansible-playbook

---
- name: Configure Alvotech hosts
  hosts: alvotech
  pre_tasks:
    - set_fact:
        docker: "{{ ansible_virtualization_type is defined and ansible_virtualization_type == 'docker' and ansible_virtualization_role == 'guest' }}"
    - debug:
        msg: "Running on Docker?: {{ docker }}"
  roles:
    - role: remote-init
      become: true
      become_user: root
    - role: geerlingguy.java
      java_packages:
        - openjdk-8-jdk
      become: true
      become_user: root
