#!/usr/bin/env ansible-playbook

---
- name: Configure Alvotech hosts
  hosts: fleet
  pre_tasks:
    - set_fact:
        docker: "{{ ansible_virtualization_type is defined and ansible_virtualization_type == 'docker' and ansible_virtualization_role == 'guest' }}"
      tags:
        - always
    - debug:
        msg: "Running on Docker?: {{ docker }}"
      tags:
        - always
  roles:
    - role: rebel-base
      become: true
      become_user: root
      tags:
        - rebel-base
    - role: java
      become: true
      become_user: root
      tags:
        - java
    - role: packt4free
      become: true
      become_user: root
      tags:
        - packt4free
    - role: telek-ansible-role
      become: true
      become_user: root
      tags:
        - telek
