#!/usr/bin/env ansible-playbook

---
- name: Configure localhost
  hosts: millennium-falcon
  pre_tasks:
    - set_fact:
        docker: "{{ ansible_virtualization_type is defined and ansible_virtualization_type == 'docker' and ansible_virtualization_role == 'guest' }}"
    - debug:
        msg: "Running on Docker?: {{ docker }}"
  roles:
    - role: millennium-falcon
      become: true
      become_user: root
      tags:
        - millennium-falcon
#    - role: java
#      become: true
#      become_user: root
#      tags:
#        - java
#    - role: maven
#      become: true
#      become_user: root
#      tags:
#        - maven
