- name: Download packt4free distribution
  get_url:
    url: https://dl.bintray.com/madhead/madhead/packt4free-{{ packt4free.version }}.zip
    dest: /tmp/packt4free-{{ packt4free.version }}.zip
- name: Create required directories
  file:
    path: '{{ packt4free.install_directory }}'
    owner: root
    group: root
    state: directory
- name: Unpack distribution
  unarchive:
    list_files: true
    src: /tmp/packt4free-{{ packt4free.version }}.zip
    dest: '{{ packt4free.install_directory }}'
    copy: false
    owner: root
    group: root
  register: unpacked
- name: Create unversioned symlink
  file:
    src: '{{ packt4free.install_directory }}/{{ (unpacked.files[0] + "/") | dirname }}'
    dest: '{{ packt4free.install_directory }}/packt4free'
    state: link
    owner: root
    group: root
- name: Check if {{ millennium_falcon.pilot }} user exists
  action: shell /usr/bin/getent passwd {{ millennium_falcon.pilot }} | /usr/bin/wc -l | tr -d ' '
  register: pilot_exists
- name: Ensure user's bin directory exists
  file:
    path: /home/{{ millennium_falcon.pilot }}/bin
    owner: '{{ millennium_falcon.pilot }}'
    group: '{{ millennium_falcon.crew }}'
    state: directory
  when: pilot_exists.rc == 0
- name: Create wrapper script
  template:
    src: packt4free.sh.j2
    dest: /home/{{ millennium_falcon.pilot }}/bin/packt4free.sh
    owner: '{{ millennium_falcon.pilot }}'
    group: '{{ millennium_falcon.crew }}'
    mode: 0700
  when: pilot_exists.rc == 0
- name: Schedule cron entry
  cron:
    name: Email about free Packt Publishing eBooks daily
    minute: 0
    hour: 1
    job: /home/{{ millennium_falcon.pilot }}/bin/packt4free.sh
    user: '{{ millennium_falcon.pilot }}'
  when: pilot_exists.rc == 0
- name: Remove temporary file
  when: global.clean_tmp
  file:
    path: /tmp/packt4free-{{ packt4free.version }}.zip
    state: absent
- name: Keep single version
  when: packt4free.single_installation
  shell: "find . -maxdepth 1 -and \\( -not -name packt4free -and -not -name {{ (unpacked.files[0] + '/') | dirname }} -and \\( -type f -or -type d -or -type l \\) \\) -exec rm -r \"{}\" \\;"
  args:
    chdir: "{{ packt4free.install_directory }}"
