- name: 'Packages : Base : Update Pacman cache'
  pacman:
    update_cache: true
- name: 'Packages : Base : Install packages'
  pacman:
    name: '{{ item }}'
    state: latest
  with_items:
    - zsh
    - vim
    - git
    - tk
    - unzip
    - yaourt
    - htop
