- name: 'Packages : Dev : Update Pacman cache'
  pacman:
    update_cache: true
- name: 'Packages : Dev : Install packages'
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    - ansible
    - atom
    - avr-gcc
    - avrdude
    - docker
    - go
    - vagrant
    - virtualbox
    - nodejs
    - npm
- name: 'Packages : Dev : Install packages from AUR'
  command: yaourt -S {{ item }} --noconfirm --needed
  with_items:
    - heroku-toolbelt
    - nvm #TODO: add to PATH
    - jetbrains-toolbox
  become: false
