- name: 'Packages : Dev : Update Pacman cache'
  pacman:
    update_cache: true
- name: 'Packages : Dev : Install packages'
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    - ansible
    - atom
    - avr-gcc
    - avrdude
    - docker
    - go
    - vagrant
    - virtualbox
    - nodejs
    - npm
- name: 'Packages : Dev : Install packages from AUR'
  command: yaourt -S {{ item }} --noconfirm --needed
  with_items:
    - heroku-toolbelt
    - nvm
    - jetbrains-toolbox
    - chef-dk
  become: false
- name: 'Packages : Dev : Install RVM'
  include_role:
    name: rvm_io.ruby
  vars:
    rvm1_user: '{{ millennium_falcon.pilot }}'
    rvm1_rubies:
      - 2.4.1
- name: 'Packages : Dev : Add NVM and RVM to PATH'
  blockinfile:
    path: /home/{{ millennium_falcon.pilot }}/.zshrc-local
    create: true
    owner: "{{ millennium_falcon.pilot }}"
    group: "{{ millennium_falcon.crew }}"
    block: |
      source /usr/share/nvm/init-nvm.sh
      source /home/{{ millennium_falcon.pilot }}/.rvm/scripts/rvm
    state: present
