- name: 'Packages : Extra : Update Pacman cache'
  pacman:
    update_cache: true
- name: 'Packages : Extra : Install packages'
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    - amarok
    - bluez
    - bluez-utils
    - calibre
    - cowsay
    - gimp
    - inkscape
    - blender
    - kdiff3
    - krusader
    - kstars
    - stellarium
    - redshift
    - wireshark-common
    - wireshark-qt
    - strace
    - rclone
    - ktorrent
    - tig
    - bind-tools
    - keepass
    - aspell-en
    - xdotool
    - youtube-dl
    - krename
    - python2-pathlib
- name: 'Packages : Extra : Install packages from AUR'
  command: yaourt -S {{ item }} --noconfirm --needed
  with_items:
    - google-chrome
    - saberlight-git
    - whatpulse
    - anki
    - hugo-bin
    - robocut
    - python-plumbum
    - python2-plumbum
    - python2-rpyc
    - python2-terminaltables
    - python2-zxcvbn
    - flexget
  become: false
- name: 'Packages : Extra : Remove unused packages'
  pacman:
    name: "{{ item }}"
    state: absent
  with_items:
    - yakuake
    - qbittorrent
