- name: Update pacman cache
  pacman:
    update_cache: true
- name: Install extra packages
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    - amarok
    - bluez
    - bluez-utils
    - calibre
    - cowsay
    - gimp
    - inkscape
    - blender
    - kdiff3
    - krusader
    - kstars
    - stellarium
    - redshift
    - wireshark-common
    - wireshark-qt
    - strace
    - rclone
    - ktorrent
    - tig
    - bind-tools
    - keepass
    - aspell-en
    - xdotool
- name: Install extra packages
  command: yaourt -S {{ item }} --noconfirm --needed
  with_items:
    - google-chrome
    - saberlight-git
    - whatpulse
    - anki
  become: false
- name: Remove unneeded packages
  pacman:
    name: "{{ item }}"
    state: absent
  with_items:
    - yakuake
    - qbittorrent
