- name: 'Packages : Games : Update Pacman cache'
  pacman:
    update_cache: true
- name: 'Packages : Games : Install packages'
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    - 0ad
    - steam-manjaro
