- import_tasks: base.yml
  tags:
    - base-packages

- import_tasks: dev.yml
  tags:
    - dev-packages

- import_tasks: extra.yml
  tags:
    - extra-packages

- import_tasks: games.yml
  tags:
    - games-packages
