- name: Set hostname from inventory
  hostname:
    name: "{{ inventory_hostname }}"
  when: not docker
- name: Fix /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  when: not docker
- name: Force UTC timezone
  copy:
    src: timezone
    dest: /etc/timezone
- name: Update tzdata
  command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata
