- include: host/main.yml
  tags:
    - host

- include: packages/main.yml
  tags:
    - packages

- include: users/main.yml
  tags:
    - users

- include: security/main.yml
  tags:
    - security
  when: not docker
