- import_tasks: host/main.yml
  tags:
    - host

- import_tasks: packages/main.yml
  tags:
    - packages

- import_tasks: users/main.yml
  tags:
    - users

- import_tasks: security/main.yml
  tags:
    - security
  when: not docker
