- name: Clone vital projects
  git:
    repo: '{{item.repo}}'
    dest: /home/{{ millennium_falcon.pilot }}/Projects/{{ item.name }}
    version: master
    accept_hostkey: true
  become: true
  become_user: '{{ millennium_falcon.pilot }}'
  ignore_errors: true
  with_items:
    - name: cfg
      repo: git@github.com:madhead/cfg.git
    - name: fleet
      repo: git@github.com:madhead/fleet.git
    - name: oh-my-zsh
      repo: git@github.com:madhead/oh-my-zsh.git
    - name: playgrounds
      repo: git@github.com:madhead/playgrounds.git
    - name: t-shirts
      repo: git@github.com:madhead/t-shirts.git
