- name: Close all ports
  ufw:
    state: enabled
    policy: deny
- name: Allow SSH connections
  ufw:
    rule: allow
    port: 22
- name: Tune SSH
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
    backup: yes
    validate: /usr/sbin/sshd -T -f %s
- name: Add Travis CI key for {{ millennium_falcon.pilot }}
  authorized_key:
    user: '{{ millennium_falcon.pilot }}'
    state: present
    key: '{{ item }}'
  with_file:
    - travis_ecdsa.pub
- name: Restart SSH
  service:
    name: ssh
    state: restarted
