- name: Update pacman cache
  pacman:
    update_cache: true
- name: Install base packages
  pacman:
    name: "{{ item }}"
    state: latest
  with_items:
    - zsh
    - vim
    - git
    - unzip
    - yaourt
    - htop
